### PR TITLE
Return updated gems

### PR DESCRIPTION
**Pull request by inkstak**
I would like to integrate bundleup into an overall update script and perform actions accordingly to the gems that have been updated.

For example:

```ruby
updates = Bundleup::CLI.new([]).run

if updates.any? && confirm?("Some gems have been updated, would you like to run tests ?")
  system "bundle exec rspec" 
end

if updates.include?("rubocop") && confirm?("Rubocop has been updated, would you like to run cops ?")
  system "bundle exec rubocop"
end

if updates.any? && confirm?("Would you like to commit changes?")
  system "git commit -m \"Update gems dependencies\" -- Gemfile.lock"
end
```

If you might consider these changes, I will try to add tests.

### CODE REVIEW

**Comment by mattbrictson** [comment]
Interesting idea! Let me think this over. I am not opposed to it, but it seems weird for `CLI#run` to return a value. A CLI, by nature, takes its inputs and provides its outputs via the command-line. So getting back an object from `run` doesn't feel right.

I would rather the `updates` be obtained by an explicit method, rather than a return value.

Something like this:

```ruby
cli = Bundleup::Cli.new([])
cli.run
updates = cli.updated_gems
```

It's a small distinction. Would that work for you?

**Comment by inkstak** [comment]
I understand and by extension it could open the way to a `pinned_gems` method for those who need it.

**Comment by mattbrictson** [comment]
@inkstak great! If you could make that small refactor and add a test, I'll merge this in. I'm also happy to add a test later, if you get stuck on that part.

**Comment by inkstak** [comment]
Done ! Some tests added and passing.
Feel free to refactor as you want ;)

**Comment by mattbrictson** [comment]
Nice! Tests look great. Much appreciated! 🙏

**Pull request merged**
